/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DbConnectionResponse } from '../../models/db-connection-response';

export interface ActivateConnection$Params {
  id: number;
}

export function activateConnection(http: HttpClient, rootUrl: string, params: ActivateConnection$Params, context?: HttpContext): Observable<StrictHttpResponse<DbConnectionResponse>> {
  const rb = new RequestBuilder(rootUrl, activateConnection.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DbConnectionResponse>;
    })
  );
}

activateConnection.PATH = '/db/{id}/activate';
