/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DbConnectionRequest } from '../../models/db-connection-request';
import { DbConnectionResponse } from '../../models/db-connection-response';

export interface CreateAndActivateConnection$Params {
  
    /**
     * Database connection details for creating and activating a connection
     */
    body: DbConnectionRequest
}

export function createAndActivateConnection(http: HttpClient, rootUrl: string, params: CreateAndActivateConnection$Params, context?: HttpContext): Observable<StrictHttpResponse<DbConnectionResponse>> {
  const rb = new RequestBuilder(rootUrl, createAndActivateConnection.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DbConnectionResponse>;
    })
  );
}

createAndActivateConnection.PATH = '/db';
