/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SchemaResponseDto } from '../../models/schema-response-dto';

export interface GetSchema$Params {
}

export function getSchema(http: HttpClient, rootUrl: string, params?: GetSchema$Params, context?: HttpContext): Observable<StrictHttpResponse<SchemaResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getSchema.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SchemaResponseDto>;
    })
  );
}

getSchema.PATH = '/db/schema';
