/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DbConnectionRequest } from '../../models/db-connection-request';
import { TestConnectionResponse } from '../../models/test-connection-response';

export interface TestConnection$Params {
      body: DbConnectionRequest
}

export function testConnection(http: HttpClient, rootUrl: string, params: TestConnection$Params, context?: HttpContext): Observable<StrictHttpResponse<TestConnectionResponse>> {
  const rb = new RequestBuilder(rootUrl, testConnection.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TestConnectionResponse>;
    })
  );
}

testConnection.PATH = '/db/test';
