/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChatMessageResponseDto {
  content?: string;
  id?: number;
  sender?: 'USER' | 'ASSISTANT';
  sentAt?: string;
}
