/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DbConnectionResponse {
  database?: string;
  dbType?: string;
  host?: string;
  id?: number;
  name?: string;
  port?: number;
  username?: string;
}
