/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface QueryHistoryResponseDto {
  connectionName?: string;
  id?: number;
  query?: string;
  queryTime?: string;
  queryType?: 'SELECT' | 'INSERT' | 'UPDATE' | 'DELETE' | 'OTHER';
}
