/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QueryResultDto } from '../../models/query-result-dto';
import { SqlRequest } from '../../models/sql-request';

export interface ExecuteSql$Params {
  
    /**
     * SQL query string to execute on the active database connection
     */
    body: SqlRequest
}

export function executeSql(http: HttpClient, rootUrl: string, params: ExecuteSql$Params, context?: HttpContext): Observable<StrictHttpResponse<QueryResultDto>> {
  const rb = new RequestBuilder(rootUrl, executeSql.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<QueryResultDto>;
    })
  );
}

executeSql.PATH = '/sql/execute';
