services:
  postgres:
    container_name: postgres-db-assistant
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: db-assistant
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    restart: unless-stopped


  postgres-test:
    container_name: postgres-test-db
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - spring-demo
    restart: unless-stopped

  postgres-vector:
    container_name: postgres-vector-db
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vector_store
    volumes:
      - postgres_vector_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - spring-demo
    restart: unless-stopped


networks:
  spring-demo:
    driver: bridge


volumes:
  postgres:
    driver: local
  postgres_test_data:
    driver: local
  postgres_vector_data:
    driver: local