/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChatMessageResponseDto } from '../../models/chat-message-response-dto';

export interface GetMessages$Params {
}

export function getMessages(http: HttpClient, rootUrl: string, params?: GetMessages$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ChatMessageResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, getMessages.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ChatMessageResponseDto>>;
    })
  );
}

getMessages.PATH = '/messages';
